[package]
name = "gcsf"
description = "Filesystem based on Google Drive"
version = "0.1.19"
repository = "https://github.com/harababurel/gcsf"
authors = ["Sergiu Puscas <srg.pscs@gmail.com>"]
license = "MIT"
keywords = ["google", "drive", "fuse", "filesystem"]
exclude = ["build/**/*.o", "doc/**/*.html", "client_secret.json"]


[dependencies]
chrono = "0.4.5"
clap = { version = "2.32.0", features = ["yaml"]}
config = "0.9.1"
ctrlc = "3.1.1"
failure = "0.1.2"
fuse = "0.3.1"
# google-drive3 = "1.0.7+20171201"
google-drive3-fork = "1.0.10"
id_tree = "1.3.0"
itertools = "0.7.8"
lazy_static = "1.1.0"
libc = "0.2.43"
log = "0.4.5"
lru_time_cache = "0.8.0"
maplit = "1.0.1"
mime-sniffer = "0.1.2"
pretty_env_logger = "0.2.4"
rand = "0.5.5"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.32"
time = "0.1.40"
xdg = "2.1.0"
yup-oauth2 = "1.0.9"

# These versions required by google-drive3
hyper = "0.10"
hyper-native-tls = "0.3"
